name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Keystore
      env:
        ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      run: |
        echo $ANDROID_KEYSTORE | base64 -d > app/keystore.jks
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}  # 确保变量名匹配
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      run: ./gradlew assembleRelease --stacktrace
    
    - name: "Upload APK"
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: app/build/outputs/apk/release/*.apk
